class arifle_ACME_base_F: Rifle_Long_Base_F
	{
		author="ajeless";
		_generalMacro="arifle_ACME_base_F";
		scope=0;
		magazines[]=
        {
            "84Rnd_8x60_Mag"
        };
        magazineWell[]=
        {
            "ACME_5x60_Quad_Mag"
        };
		reloadAction="ReloadGM6";
		recoil="recoil_ACME_MCR22";
		maxZeroing=2200;
		cursor="srifle";
		// maxRecoilSway=0.029999999;
		// swayDecaySpeed=1.25;
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\A3\Weapons_F\LongRangeRifles\GM6\Data\Anim\GM6.rtm"
		};
		// opticsPPEffects[]={};
		// opticsFlare=1;
		// opticsDisablePeripherialVision=1;
		// class GunParticles
		// {
		// 	class FirstEffect
		// 	{
		// 		effectName="SniperCloud";
		// 		positionName="Usti hlavne";
		// 		directionName="Konec hlavne";
		// 	};
		// };
		distanceZoomMin=300;
		distanceZoomMax=350;
		bullet1[]=
		{
			"A3\sounds_f\weapons\shells\7_62\metal_762_01",
			0.79432821,
			1,
			15
		};
		bullet2[]=
		{
			"A3\sounds_f\weapons\shells\7_62\metal_762_02",
			0.79432821,
			1,
			15
		};
		bullet3[]=
		{
			"A3\sounds_f\weapons\shells\7_62\metal_762_03",
			0.79432821,
			1,
			15
		};
		bullet4[]=
		{
			"A3\sounds_f\weapons\shells\7_62\metal_762_04",
			0.79432821,
			1,
			15
		};
		bullet5[]=
		{
			"A3\sounds_f\weapons\shells\7_62\dirt_762_01",
			0.79432821,
			1,
			15
		};
		bullet6[]=
		{
			"A3\sounds_f\weapons\shells\7_62\dirt_762_02",
			0.79432821,
			1,
			15
		};
		bullet7[]=
		{
			"A3\sounds_f\weapons\shells\7_62\dirt_762_03",
			0.79432821,
			1,
			15
		};
		bullet8[]=
		{
			"A3\sounds_f\weapons\shells\7_62\dirt_762_04",
			0.79432821,
			1,
			15
		};
		bullet9[]=
		{
			"A3\sounds_f\weapons\shells\7_62\grass_762_01",
			0.70794576,
			1,
			15
		};
		bullet10[]=
		{
			"A3\sounds_f\weapons\shells\7_62\grass_762_02",
			0.70794576,
			1,
			15
		};
		bullet11[]=
		{
			"A3\sounds_f\weapons\shells\7_62\grass_762_03",
			0.70794576,
			1,
			15
		};
		bullet12[]=
		{
			"A3\sounds_f\weapons\shells\7_62\grass_762_04",
			0.70794576,
			1,
			15
		};
		soundBullet[]=
		{
			"bullet1",
			0.082999997,
			"bullet2",
			0.082999997,
			"bullet3",
			0.082999997,
			"bullet4",
			0.082999997,
			"bullet5",
			0.082999997,
			"bullet6",
			0.082999997,
			"bullet7",
			0.082999997,
			"bullet8",
			0.082999997,
			"bullet9",
			0.082999997,
			"bullet10",
			0.082999997,
			"bullet11",
			0.082999997,
			"bullet12",
			0.082999997
		};
        class Library
		{
			libTextDesc="ACME MCR base configuration";
		};
		modes[]=
		{
			"Single",
            "Burst",
            "Burst_medium",
            "Full_auto",
			"far_optic1",
			"medium_optic2",
			"far_optic2"
		};
		drySound[]=
		{
			"A3\Sounds_F\arsenal\weapons\LongRangeRifles\GM6_Lynx\GM6_dry",
			0.56234133,
			1,
			15
		};
		reloadMagazineSound[]=
		{
			"A3\Sounds_F\arsenal\weapons\LongRangeRifles\GM6_Lynx\GM6_reload",
			1,
			1,
			10
		};
		soundBipodDeploy[]=
		{
			"A3\Sounds_F_Mark\arsenal\sfx\bipods\Bipod_generic_deploy",
			0.70794576,
			1,
			20
		};
		soundBipodFold[]=
		{
			"A3\Sounds_F_Mark\arsenal\sfx\bipods\Bipod_generic_fold",
			0.70794576,
			1,
			20
		};
		soundBipodDown[]=
		{
			"A3\Sounds_F_Mark\arsenal\sfx\bipods\Bipod_generic_down",
			0.70794576,
			1,
			20
		};
		soundBipodUp[]=
		{
			"A3\Sounds_F_Mark\arsenal\sfx\bipods\Bipod_generic_up",
			0.70794576,
			1,
			20
		};
        class Single: Mode_SemiAuto
        {
            sounds[]=
            {
                "StandardSound",
                "SilencedSound"
            };
            class BaseSoundModeType;
            class StandardSound: BaseSoundModeType
            {
                begin1[]=
                {
                    "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\MMG_02_short_01",
                    1.2589254,
                    1,
                    1200
                };
                begin2[]=
                {
                    "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\MMG_02_short_02",
                    1.2589254,
                    1,
                    1200
                };
                begin3[]=
                {
                    "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\MMG_02_short_03",
                    1.2589254,
                    1,
                    1200
                };
                soundBegin[]=
                {
                    "begin1",
                    0.34,
                    "begin2",
                    0.33000001,
                    "begin3",
                    0.33000001
                };
                class SoundTails
                {
                    class TailInterior
                    {
                        sound[]=
                        {
                            "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\MMG_02_tail_interior",
                            1,
                            1,
                            1200
                        };
                        frequency=1;
                        volume="interior";
                    };
                    class TailForest
                    {
                        sound[]=
                        {
                            "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\MMG_02_tail_forest",
                            1,
                            1,
                            1200
                        };
                        frequency=1;
                        volume="(1-interior/1.4)*forest";
                    };
                    class TailHouses
                    {
                        sound[]=
                        {
                            "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\MMG_02_tail_houses",
                            1,
                            1,
                            1200
                        };
                        frequency=1;
                        volume="(1-interior/1.4)*houses";
                    };
                    class TailMeadows
                    {
                        sound[]=
                        {
                            "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\MMG_02_tail_meadows",
                            1,
                            1,
                            1200
                        };
                        frequency=1;
                        volume="(1-interior/1.4)*(meadows/2 max sea/2)";
                    };
                    class TailTrees
                    {
                        sound[]=
                        {
                            "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\MMG_02_tail_trees",
                            1,
                            1,
                            1200
                        };
                        frequency=1;
                        volume="(1-interior/1.4)*trees";
                    };
                };
            };
            class SilencedSound: BaseSoundModeType
            {
                begin1[]=
                {
                    "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\silencer_MMG_02_short_01",
                    1,
                    1,
                    300
                };
                begin2[]=
                {
                    "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\silencer_MMG_02_short_02",
                    1,
                    1,
                    300
                };
                begin3[]=
                {
                    "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\silencer_MMG_02_short_03",
                    1,
                    1,
                    300
                };
                soundBegin[]=
                {
                    "begin1",
                    0.33000001,
                    "begin2",
                    0.33000001,
                    "begin3",
                    0.34
                };
                class SoundTails
                {
                    class TailInterior
                    {
                        sound[]=
                        {
                            "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\silencer_MMG_02_tail_interior",
                            1,
                            1,
                            300
                        };
                        frequency=1;
                        volume="interior";
                    };
                    class TailForest
                    {
                        sound[]=
                        {
                            "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\silencer_MMG_02_tail_forest",
                            1,
                            1,
                            300
                        };
                        frequency=1;
                        volume="(1-interior/1.4)*forest";
                    };
                    class TailHouses
                    {
                        sound[]=
                        {
                            "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\silencer_MMG_02_tail_houses",
                            1,
                            1,
                            300
                        };
                        frequency=1;
                        volume="(1-interior/1.4)*houses";
                    };
                    class TailMeadows
                    {
                        sound[]=
                        {
                            "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\silencer_MMG_02_tail_meadows",
                            1,
                            1,
                            300
                        };
                        frequency=1;
                        volume="(1-interior/1.4)*(meadows/2 max sea/2)";
                    };
                    class TailTrees
                    {
                        sound[]=
                        {
                            "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\silencer_MMG_02_tail_trees",
                            1,
                            1,
                            300
                        };
                        frequency=1;
                        volume="(1-interior/1.4)*trees";
                    };
                };
            };
            reloadTime=0.08;
            dispersion=0.00086999999;
            minRange=2;
            minRangeProbab=0.5;
            midRange=150;
            midRangeProbab=0.69999999;
            maxRange=250;
            maxRangeProbab=0.2;
        };
        class Full_auto: Mode_FullAuto
        {
            sounds[]=
            {
                "StandardSound",
                "SilencedSound"
            };
            class BaseSoundModeType
            {
                closure1[]=
                {
                    "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\MMG_02_Closure_01",
                    0.44668359,
                    1,
                    10
                };
                closure2[]=
                {
                    "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\MMG_02_Closure_02",
                    0.44668359,
                    1,
                    10
                };
                soundClosure[]=
                {
                    "closure1",
                    0.5,
                    "closure2",
                    0.5
                };
            };
            class StandardSound: BaseSoundModeType
            {
                begin1[]=
                {
                    "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\MMG_02_short_01",
                    1.2589254,
                    1,
                    1200
                };
                begin2[]=
                {
                    "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\MMG_02_short_02",
                    1.2589254,
                    1,
                    1200
                };
                begin3[]=
                {
                    "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\MMG_02_short_03",
                    1.2589254,
                    1,
                    1200
                };
                soundBegin[]=
                {
                    "begin1",
                    0.34,
                    "begin2",
                    0.33000001,
                    "begin3",
                    0.33000001
                };
                class SoundTails
                {
                    class TailInterior
                    {
                        sound[]=
                        {
                            "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\MMG_02_tail_interior",
                            1,
                            1,
                            1200
                        };
                        frequency=1;
                        volume="interior";
                    };
                    class TailForest
                    {
                        sound[]=
                        {
                            "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\MMG_02_tail_forest",
                            1,
                            1,
                            1200
                        };
                        frequency=1;
                        volume="(1-interior/1.4)*forest";
                    };
                    class TailHouses
                    {
                        sound[]=
                        {
                            "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\MMG_02_tail_houses",
                            1,
                            1,
                            1200
                        };
                        frequency=1;
                        volume="(1-interior/1.4)*houses";
                    };
                    class TailMeadows
                    {
                        sound[]=
                        {
                            "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\MMG_02_tail_meadows",
                            1,
                            1,
                            1200
                        };
                        frequency=1;
                        volume="(1-interior/1.4)*(meadows/2 max sea/2)";
                    };
                    class TailTrees
                    {
                        sound[]=
                        {
                            "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\MMG_02_tail_trees",
                            1,
                            1,
                            1200
                        };
                        frequency=1;
                        volume="(1-interior/1.4)*trees";
                    };
                };
            };
            class SilencedSound: BaseSoundModeType
            {
                begin1[]=
                {
                    "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\silencer_MMG_02_short_01",
                    1,
                    1,
                    300
                };
                begin2[]=
                {
                    "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\silencer_MMG_02_short_02",
                    1,
                    1,
                    300
                };
                begin3[]=
                {
                    "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\silencer_MMG_02_short_03",
                    1,
                    1,
                    300
                };
                soundBegin[]=
                {
                    "begin1",
                    0.33000001,
                    "begin2",
                    0.33000001,
                    "begin3",
                    0.34
                };
                class SoundTails
                {
                    class TailInterior
                    {
                        sound[]=
                        {
                            "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\silencer_MMG_02_tail_interior",
                            1,
                            1,
                            300
                        };
                        frequency=1;
                        volume="interior";
                    };
                    class TailForest
                    {
                        sound[]=
                        {
                            "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\silencer_MMG_02_tail_forest",
                            1,
                            1,
                            300
                        };
                        frequency=1;
                        volume="(1-interior/1.4)*forest";
                    };
                    class TailHouses
                    {
                        sound[]=
                        {
                            "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\silencer_MMG_02_tail_houses",
                            1,
                            1,
                            300
                        };
                        frequency=1;
                        volume="(1-interior/1.4)*houses";
                    };
                    class TailMeadows
                    {
                        sound[]=
                        {
                            "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\silencer_MMG_02_tail_meadows",
                            1,
                            1,
                            300
                        };
                        frequency=1;
                        volume="(1-interior/1.4)*(meadows/2 max sea/2)";
                    };
                    class TailTrees
                    {
                        sound[]=
                        {
                            "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\silencer_MMG_02_tail_trees",
                            1,
                            1,
                            300
                        };
                        frequency=1;
                        volume="(1-interior/1.4)*trees";
                    };
                };
            };
            reloadTime=0.115;
            dispersion=0.00073000003;
            // soundContinuous=0;
            // soundBurst=0;
        };
        class Burst: Mode_Burst
        {
            sounds[]=
            {
                "StandardSound",
                "SilencedSound"
            };
            class BaseSoundModeType
            {
                closure1[]=
                {
                    "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\MMG_02_Closure_01",
                    0.44668359,
                    1,
                    10
                };
                closure2[]=
                {
                    "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\MMG_02_Closure_02",
                    0.44668359,
                    1,
                    10
                };
                soundClosure[]=
                {
                    "closure1",
                    0.5,
                    "closure2",
                    0.5
                };
            };
            class StandardSound: BaseSoundModeType
            {
                begin1[]=
                {
                    "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\MMG_02_short_01",
                    1.2589254,
                    1,
                    1200
                };
                begin2[]=
                {
                    "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\MMG_02_short_02",
                    1.2589254,
                    1,
                    1200
                };
                begin3[]=
                {
                    "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\MMG_02_short_03",
                    1.2589254,
                    1,
                    1200
                };
                soundBegin[]=
                {
                    "begin1",
                    0.34,
                    "begin2",
                    0.33000001,
                    "begin3",
                    0.33000001
                };
                class SoundTails
                {
                    class TailInterior
                    {
                        sound[]=
                        {
                            "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\MMG_02_tail_interior",
                            1,
                            1,
                            1200
                        };
                        frequency=1;
                        volume="interior";
                    };
                    class TailForest
                    {
                        sound[]=
                        {
                            "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\MMG_02_tail_forest",
                            1,
                            1,
                            1200
                        };
                        frequency=1;
                        volume="(1-interior/1.4)*forest";
                    };
                    class TailHouses
                    {
                        sound[]=
                        {
                            "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\MMG_02_tail_houses",
                            1,
                            1,
                            1200
                        };
                        frequency=1;
                        volume="(1-interior/1.4)*houses";
                    };
                    class TailMeadows
                    {
                        sound[]=
                        {
                            "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\MMG_02_tail_meadows",
                            1,
                            1,
                            1200
                        };
                        frequency=1;
                        volume="(1-interior/1.4)*(meadows/2 max sea/2)";
                    };
                    class TailTrees
                    {
                        sound[]=
                        {
                            "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\MMG_02_tail_trees",
                            1,
                            1,
                            1200
                        };
                        frequency=1;
                        volume="(1-interior/1.4)*trees";
                    };
                };
            };
            class SilencedSound: BaseSoundModeType
            {
                begin1[]=
                {
                    "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\silencer_MMG_02_short_01",
                    1,
                    1,
                    300
                };
                begin2[]=
                {
                    "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\silencer_MMG_02_short_02",
                    1,
                    1,
                    300
                };
                begin3[]=
                {
                    "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\silencer_MMG_02_short_03",
                    1,
                    1,
                    300
                };
                soundBegin[]=
                {
                    "begin1",
                    0.33000001,
                    "begin2",
                    0.33000001,
                    "begin3",
                    0.34
                };
                class SoundTails
                {
                    class TailInterior
                    {
                        sound[]=
                        {
                            "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\silencer_MMG_02_tail_interior",
                            1,
                            1,
                            300
                        };
                        frequency=1;
                        volume="interior";
                    };
                    class TailForest
                    {
                        sound[]=
                        {
                            "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\silencer_MMG_02_tail_forest",
                            1,
                            1,
                            300
                        };
                        frequency=1;
                        volume="(1-interior/1.4)*forest";
                    };
                    class TailHouses
                    {
                        sound[]=
                        {
                            "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\silencer_MMG_02_tail_houses",
                            1,
                            1,
                            300
                        };
                        frequency=1;
                        volume="(1-interior/1.4)*houses";
                    };
                    class TailMeadows
                    {
                        sound[]=
                        {
                            "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\silencer_MMG_02_tail_meadows",
                            1,
                            1,
                            300
                        };
                        frequency=1;
                        volume="(1-interior/1.4)*(meadows/2 max sea/2)";
                    };
                    class TailTrees
                    {
                        sound[]=
                        {
                            "A3\Sounds_F_Mark\arsenal\weapons\Machineguns\MMG_02_SPGM\silencer_MMG_02_tail_trees",
                            1,
                            1,
                            300
                        };
                        frequency=1;
                        volume="(1-interior/1.4)*trees";
                    };
                };
            };
            textureType="dual";
            burst=3;
            reloadTime=0.11;
            dispersion=0.00086999999;
            minRange=2;
            minRangeProbab=0.89999998;
            midRange=50;
            midRangeProbab=0.69999999;
            maxRange=100;
            maxRangeProbab=0.050000001;
        };
		class Burst_medium: Burst
        {
            showToPlayer=0;
            minRange=2;
            minRangeProbab=0.5;
            midRange=75;
            midRangeProbab=0.69999999;
            maxRange=100;
            maxRangeProbab=0.050000001;
            aiRateOfFire=2;
        };
        class close: Full_auto
        {
            burst=10;
            aiRateOfFire=0.5;
            aiRateOfFireDistance=50;
            minRange=0;
            minRangeProbab=0.050000001;
            midRange=25;
            midRangeProbab=0.69999999;
            maxRange=50;
            maxRangeProbab=0.039999999;
            showToPlayer=0;
        };
		class far_optic1: Single
		{
			showToPlayer=0;
			minRange=150;
			minRangeProbab=0.2;
			midRange=500;
			midRangeProbab=0.69999999;
			maxRange=1500;
			maxRangeProbab=0.40000001;
			aiRateOfFire=3;
			aiRateOfFireDistance=500;
			requiredOpticType=1;
		};
		class medium_optic2: Single
		{
			showToPlayer=0;
			minRange=250;
			minRangeProbab=0.2;
			midRange=750;
			midRangeProbab=0.69999999;
			maxRange=1000;
			maxRangeProbab=0.40000001;
			aiRateOfFire=5;
			aiRateOfFireDistance=1000;
			requiredOpticType=2;
		};
		class far_optic2: far_optic1
		{
			minRange=500;
			minRangeProbab=0.2;
			midRange=1200;
			midRangeProbab=0.69999999;
			maxRange=2100;
			maxRangeProbab=0.30000001;
			aiRateOfFire=7;
			aiRateOfFireDistance=1000;
			requiredOpticType=2;
		};
	};
	class arifle_ACME_MCR22: arifle_ACME_base_F
	{
		author="ajeless";
		_generalMacro="arifle_ACME_MCR22";
		baseWeapon="arifle_ACME_MCR22";
		scope=2;
		model="\A3\Weapons_F\LongRangeRifles\GM6\GM6_F.p3d";
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=240;
			class MuzzleSlot: MuzzleSlot
            {
                linkProxy="\A3\data_f\proxies\weapon_slots\MUZZLE";
                compatibleItems[]=
				{
					"muzzle_snds_93mmg"
				};
                iconPosition[]={0,0.34999999};
                iconScale=0.2;
            };
			class CowsSlot: CowsSlot
			{
				iconPosition[]={0.55000001,0.30000001};
				iconScale=0.2;
			};
			class PointerSlot
			{
			};
		};
		inertia=1.2;
		aimTransitionSpeed=0.5;
		dexterity=1;
		class ItemInfo
		{
			priority=1;
		};
		displayName="ACME MCR-22 (Black, 8.5x64)";
		picture="\A3\Weapons_F\LongRangeRifles\GM6\Data\UI\gear_gm6_X_CA.paa";
		UiPicture="\A3\weapons_f\data\UI\icon_sniper_CA.paa";
		descriptionShort="ACME MCR-21 (8.5x64)mm Multirole Combat Rifle";
	};