class CfgPatches {
    class I_MYF {
        units[] = {
            "I_MYF_MY_Unit_01"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        requiredAddons[] = {
            "A3_Characters_F",
            "A3_Sounds_F",
            "A3_Sounds_F_Exp",
            "A3_Data_F",
            "A3_Data_F_Curator",
            "A3_Air_F_Heli",
            "gm_worlds_weferlingen_summer_cfg",
            "cba_xeh"
        };
        author = "ajeless";
        authors[] = {"ajeless"};
    };
};

//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 200.146773 on Stable branch
// Generated with ALiVE version 1.12.1.2002131
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class I_MYF {
        displayName = "MyFaction";
        side = 2;
        flag = "\A3\ui_f\data\map\markers\flags\UN_ca.paa";
        icon = "\A3\ui_f\data\map\markers\flags\UN_ca.paa";
        priority = 0;
    };
};


//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 200.146773 on Stable branch
// Generated with ALiVE version 1.12.1.2002131
//////////////////////////////////////////////////////////////////////////////////


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class I_G_Soldier_F;
    class I_G_Soldier_F_OCimport_01 : I_G_Soldier_F { scope = 0; class EventHandlers; };
    class I_G_Soldier_F_OCimport_02 : I_G_Soldier_F_OCimport_01 { class EventHandlers; };


    class I_MYF_MY_Unit_01 : I_G_Soldier_F_OCimport_02 {
        author = "ajeless";
        scope = 2;
        scopeCurator = 2;
        displayName = "MY Unit";
        side = 2;
        faction = "I_MYF";

        identityTypes[] = {"Head_Asian","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "U_I_L_Uniform_01_deserter_F";

        linkedItems[] = {"gm_ge_army_vest_80_crew","H_Construction_earprot_red_F","ItemMap","B_UavTerminal","gm_gc_compass_f73","ItemWatch"};
        respawnlinkedItems[] = {"gm_ge_army_vest_80_crew","H_Construction_earprot_red_F","ItemMap","B_UavTerminal","gm_gc_compass_f73","ItemWatch"};

        weapons[] = {"LMG_Mk200_F","launch_O_Vorona_green_F","hgun_P07_khk_F","gm_ferod16_des"};
        respawnWeapons[] = {"LMG_Mk200_F","launch_O_Vorona_green_F","hgun_P07_khk_F","gm_ferod16_des"};

        magazines[] = {"200Rnd_65x39_cased_Box","Vorona_HEAT","16Rnd_9x21_Mag","200Rnd_65x39_cased_Box","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"200Rnd_65x39_cased_Box","Vorona_HEAT","16Rnd_9x21_Mag","200Rnd_65x39_cased_Box","16Rnd_9x21_Mag"};

        backpack = "I_E_UAV_01_backpack_F";

        // ALiVE_orbatCreator_loadout[] = {{"LMG_Mk200_F","muzzle_snds_H_MG","","",{"200Rnd_65x39_cased_Box",200},{},""},{"launch_O_Vorona_green_F","","","",{"Vorona_HEAT",1},{},""},{"hgun_P07_khk_F","","","",{"16Rnd_9x21_Mag",16},{},""},{"U_I_L_Uniform_01_deserter_F",{{"FirstAidKit",1},{"MiniGrenade",1,1},{"16Rnd_9x21_Mag",2,16}}},{"gm_ge_army_vest_80_crew",{{"HandGrenade",1,1},{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"Chemlight_blue",2,1},{"200Rnd_65x39_cased_Box",1,200},{"16Rnd_9x21_Mag",1,16}}},{"I_E_UAV_01_backpack_F",{}},"H_Construction_earprot_red_F","G_Bandanna_blk",{"gm_ferod16_des","","","",{},{},""},{"ItemMap","B_UavTerminal","","gm_gc_compass_f73","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            // class ALiVE_orbatCreator {
            //     init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'gm_armpatch_ltg61'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            // };

        };

        // custom attributes (do not delete)
        // ALiVE_orbatCreator_owned = 1;
        // ALiVE_orbatCreator_insignia = "gm_armpatch_ltg61";

    };

};